import { useEffect, useState } from "react";
import { getDuas, getSurahs } from "../lib/api.js";
import { ArabesqueDivider } from "../components/Pattern.jsx";

export default function About() {
  const [counts, setCounts] = useState({ duas: 0, cats: 0, surahs: 0 });

  useEffect(() => {
    Promise.all([getDuas(), getSurahs()]).then(([d, s]) => {
      setCounts({ duas: d.length, cats: new Set(d.map((x) => x.category)).size, surahs: s.length });
    });
  }, []);

  return (
    <div className="prose">
      <h1 style={{ fontSize: "2.1rem" }}>Credits &amp; Sources</h1>
      <p>
        Noorly is a non-commercial learning app for children. Every piece of text and
        audio here comes from established, openly-available Islamic sources, listed
        below exactly as used. It currently carries <b>{counts.duas} duas</b> across{" "}
        <b>{counts.cats} categories</b>, plus <b>Surah Al-Fatiha</b> and all{" "}
        <b>37 surahs</b> of Juz 30.
      </p>

      <ArabesqueDivider />

      <h2>Qur'an — recitation audio</h2>
      <div className="credit-card">
        <h3>Reciter: Mishary Rashid Alafasy</h3>
        <p>
          Surah recitation is streamed (not rehosted) from two openly-available sources
          in the Qur'an audio ecosystem:
        </p>
        <ul>
          <li>Full-surah word-synced audio via <a href="https://quran.com" target="_blank" rel="noreferrer">Quran.com / QuranicAudio</a> (<code>quranicaudio.com</code>).</li>
          <li>Per-ayah fallback audio via <a href="https://everyayah.com" target="_blank" rel="noreferrer">EveryAyah.com</a>, folder <code>Alafasy_128kbps</code>.</li>
        </ul>
      </div>

      <h2>Qur'an — text, translation &amp; word timing</h2>
      <div className="credit-card">
        <h3>Al Quran Cloud API</h3>
        <p>Ayah translations use the <b>Muhammad Asad</b> English edition (<code>en.asad</code>) and the English transliteration edition, via <a href="https://alquran.cloud" target="_blank" rel="noreferrer">alquran.cloud</a>.</p>
      </div>
      <div className="credit-card">
        <h3>Quran.com API (v4)</h3>
        <p>
          Uthmani Arabic text, per-word transliteration &amp; glosses, and the
          precomputed <b>word-by-word timing segments</b> that power the highlighting
          come from the <a href="https://api-docs.quran.com" target="_blank" rel="noreferrer">Quran.com API</a>.
        </p>
      </div>

      <h2>Duas — recitation audio</h2>
      <div className="credit-card">
        <h3>Reciter: Shaykh Yahya Hawwa</h3>
        <p>
          The dua recitations are by Hafiz <b>Shaykh Yahya Hawwa</b>, whose reading of
          <i> Hisnul Muslim</i> is the one carried across the Fortress of the Muslim audio
          editions. The audio is streamed (not rehosted) from{" "}
          <a href="https://www.hisnmuslim.com" target="_blank" rel="noreferrer">hisnmuslim.com</a>.
        </p>
      </div>

      <h2>Duas — text &amp; translation</h2>
      <div className="credit-card">
        <h3>Hisnul Muslim (Fortress of the Muslim)</h3>
        <p>
          Arabic text, English translation and transliteration for the duas are drawn
          from the open <a href="https://github.com/wafaaelmaandy/Hisn-Muslim-Json" target="_blank" rel="noreferrer">Hisn-Muslim-Json</a> dataset,
          compiled from the book <i>Hisnul Muslim</i> by Sa'id bin Ali bin Wahf al-Qahtani.
          Well-known duas carry their specific hadith references (Bukhari, Muslim, Abu Dawud, Tirmidhi, Ibn Majah);
          the rest cite the Hisnul Muslim chapter they belong to.
        </p>
      </div>
      <div className="credit-card">
        <h3>Word-by-word dua timing — generated by forced alignment</h3>
        <p>
          Unlike the Qur'an, dua audio ships with no per-word timing. Noorly generates it
          locally with <b>forced alignment</b> (OpenAI Whisper via <code>faster-whisper</code>):
          each dua's known Arabic text is aligned to its recitation to recover real per-word
          timestamps and the exact audio segment for that dua. All <b>{counts.duas}</b> duas
          are word-synced this way.
        </p>
      </div>

      <h2>Visuals</h2>
      <div className="credit-card">
        <h3>Meaning-driven scene images</h3>
        <p>
          Each ayah is matched to a calm <b>Ghibli-style landscape</b>, and each dua to a
          gentle, child-friendly scene that reflects the meaning of the words. These
          backgrounds were generated locally with a free, <b>open-source AI image model</b>.
          The animated SVG scenes are used as a fallback where an image is unavailable.
        </p>
      </div>

      <ArabesqueDivider />

      <h2>Found a mistake? Help us keep it accurate</h2>
      <div className="credit-card">
        <p>
          Accuracy matters most when it comes to the Qur'an and the authentic duas.
          We've taken great care with every ayah and dua, but if you ever notice a
          <b> misquote, an incorrect translation or transliteration, a wrong reference,
          or a highlight that's out of sync</b>, please tell us so we can put it right.
        </p>
        <p>
          Email us at{" "}
          <a href="mailto:mudasirqadirbhat@gmail.com?subject=Noorly%20%E2%80%94%20correction">mudasirqadirbhat@gmail.com</a>{" "}
          and please mention <b>which surah or dua</b> it is and <b>what the issue is</b>,
          so we can review and rectify it quickly. Jazak Allahu khayran for helping us get it right.
        </p>
      </div>
    </div>
  );
}
