// Support / "buy me a coffee" config. Fill in your links below.
export const SUPPORT = {
  headline: "Enjoying Noorly? ☕",
  message:
    "Noorly is free and ad-free. If it helps your family, a small tip keeps it growing and covers hosting. JazakumAllahu khayran! 🤍",

  // ---- GLOBAL payment link (works worldwide: cards / PayPal / Apple & Google Pay) ----
  primary: {
    label: "Donate with PayPal",
    url: "https://paypal.me/mudasirqadir",
  },

  // ---- UPI for supporters in India (zero fees, instant) ----
  upi: {
    id: "mudasirmailg@okaxis",
    name: "Mudasir Qadir",
    qr: "/upi-qr.png", // generated by scripts/generate-upi-qr.mjs
  },
};

// Build a upi:// deep link (opens GPay/PhonePe/Paytm on mobile).
export function upiLink({ id, name }, amount) {
  const p = new URLSearchParams({ pa: id, pn: name || "Noorly", cu: "INR" });
  if (amount) p.set("am", String(amount));
  return `upi://pay?${p.toString()}`;
}
